export const HOME_PRODUCTS_REQUEST = "HOME_PRODUCTS_REQUEST";
export const LOADING_REQUEST = "LOADING_REQUEST";
export const GET_PRODUCTS_SUCCESSFUL = "GET_PRODUCTS_SUCCESSFUL";
export const ERROR_REQUEST = "ERROR_REQUEST";

export const GET_SINGLE_PRODUCT_REQUEST = "GET_SINGLE_PRODUCT_REQUEST";

export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const GET_CART_DATA_REQUEST = "GET_CART_DATA_REQUEST";
