export const LOADING_REQUEST = "LOADING_REQUEST";
export const ERROR_REQUEST = "ERROR_REQUEST";

export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const GET_CART_DATA_REQUEST = "GET_CART_DATA_REQUEST";

export const QUANTITY_INCREMENT = "QUANTITY_INCREMENT";
export const QUANTITY_DECREMENT = "QUANTITY_DECREMENT";
